
(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const tools=[
{id:'pdf',icon:'▣',name:'Image → PDF ≤100 KB',desc:'Combine images into a compact PDF and automatically optimize toward your chosen size.',feature:true,tag:'FILE TOOL'},
{id:'age',icon:'◷',name:'Age Calculator',desc:'Calculate exact age in years, months and days from a birth date.'},
{id:'percent',icon:'%',name:'Percentage Calculator',desc:'Find a percentage of a number or calculate percentage change.'},
{id:'calc',icon:'＋',name:'Smart Calculator',desc:'Full arithmetic keypad with +, −, ×, ÷, %, decimals and parentheses.'},
{id:'units',icon:'⇄',name:'Unit Converter',desc:'Convert length, weight, temperature and area instantly.'},
{id:'discount',icon:'⌁',name:'Discount Calculator',desc:'See final price, savings and effective discount in seconds.'},
{id:'emi',icon:'₹',name:'EMI Calculator',desc:'Estimate monthly loan payment, total interest and total repayment.'},
{id:'bmi',icon:'◉',name:'BMI Calculator',desc:'Calculate BMI from height and weight with a clear result.'},
{id:'password',icon:'⌁',name:'Password Generator',desc:'Generate strong random passwords locally on your device.'},
{id:'words',icon:'Aa',name:'Text Counter',desc:'Count words, characters, lines and estimated reading time.'}
];
const grid=$('#grid');
tools.forEach((t,i)=>{const c=document.createElement('article');c.className='card'+(t.feature?' feature':'');c.dataset.name=(t.name+' '+t.desc).toLowerCase();c.innerHTML=`${t.tag?`<span class="tag">${t.tag}</span>`:''}<div class="icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p><button class="open" data-open="${t.id}">Open →</button>`;grid.appendChild(c)});
const view=$('#toolview'),body=$('#toolBody'),name=$('#toolName');
let activeTool=null;
let historyClosing=false;
function renderTool(id){const t=tools.find(x=>x.id===id);if(!t)return;activeTool=id;name.textContent=t.name;body.innerHTML=template(id);view.classList.add('show');document.body.style.overflow='hidden';requestAnimationFrame(()=>{const f=init[id];if(f)f();});}
function openTool(id){const t=tools.find(x=>x.id===id);if(!t)return;renderTool(id);
  // Create a real browser history entry so Android/browser Back returns to the Tools page
  // instead of leaving the local website.
  if(!historyClosing){history.pushState({harshTool:id},'',`#tool=${encodeURIComponent(id)}`);}
  historyClosing=false;
}
function closeTool(fromPopstate=false){
  if(!view.classList.contains('show'))return;
  view.classList.remove('show');document.body.style.overflow='';body.innerHTML='';activeTool=null;
  if(!fromPopstate && history.state && history.state.harshTool){historyClosing=true;history.back();}
}
grid.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openTool(b.dataset.open)});
$('#closeTool').onclick=()=>closeTool(false);
window.addEventListener('popstate',e=>{
  if(e.state && e.state.harshTool){renderTool(e.state.harshTool);}
  else closeTool(true);
});
// Support opening a tool from a shared/bookmarked #tool=... URL.
window.addEventListener('load',()=>{const m=location.hash.match(/^#tool=([^&]+)/);if(m){const id=decodeURIComponent(m[1]);if(tools.some(t=>t.id===id)){history.replaceState({harshTool:id},'',location.href);renderTool(id);}}});
$('#searchBtn').onclick=()=>{const q=$('#toolSearch').value.trim().toLowerCase();document.querySelectorAll('.card').forEach(c=>c.style.display=!q||c.dataset.name.includes(q)?'':'none');document.querySelector('#tools').scrollIntoView({behavior:'smooth'});};
$('#toolSearch').addEventListener('keydown',e=>{if(e.key==='Enter')$('#searchBtn').click()});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&view.classList.contains('show'))closeTool()});
function template(id){
if(id==='pdf')return `<h1>Image → PDF ≤100 KB</h1><p class="sub">Add one or more images. HarshTools compresses them locally and builds a real PDF, aiming for the exact target size.</p><div class="box"><div class="drop" id="pdfdrop"><label for="pdffiles">Choose images</label><div>or drag & drop here</div><input id="pdffiles" type="file" accept="image/*" multiple></div><div class="preview" id="pdfpreview"></div><div class="row" style="margin-top:15px"><div class="field"><label>Target size (KB)</label><input id="ptarget" type="number" min="20" max="5000" value="100"></div><div class="field"><label>Page format</label><select id="pformat"><option value="a4">A4</option><option value="letter">Letter</option></select></div></div><div class="actions"><button class="primary" id="pdfgo">Create optimized PDF</button><button class="secondary" id="pdfclear">Clear</button></div><div class="meter"><i id="pmeter"></i></div><div class="result" id="pdfres">Ready.</div><p class="notice">Forcing a PDF below 100 KB is mathematically dependent on image content. If the target cannot be reached without destroying readability, the tool reports the best result instead of pretending.</p></div>`;
if(id==='age')return `<h1>Age Calculator</h1><p class="sub">Get an exact age breakdown from a birth date to today or a date you choose.</p><div class="box"><div class="row"><div class="field"><label>Date of birth</label><input id="dob" type="date"></div><div class="field"><label>Calculate on</label><input id="agedate" type="date"></div></div><div class="actions"><button class="primary" id="agego">Calculate age</button></div><div class="result" id="ageres">Enter both dates.</div></div>`;
if(id==='percent')return `<h1>Percentage Calculator</h1><p class="sub">Two practical modes: percentage of a number and percentage change between two values.</p><div class="box"><h3>What is X% of Y?</h3><div class="row"><div class="field"><label>Percentage X</label><input id="px" type="number" step="any" value="10"></div><div class="field"><label>Number Y</label><input id="py" type="number" step="any" value="250"></div></div><div class="actions"><button class="primary" id="pgo">Calculate</button></div><div class="result" id="pres">10% of 250 = 25.</div></div><div class="box"><h3>Percentage change</h3><div class="row"><div class="field"><label>Original value</label><input id="pold" type="number" step="any" value="100"></div><div class="field"><label>New value</label><input id="pnew" type="number" step="any" value="125"></div></div><div class="actions"><button class="primary" id="pchange">Calculate change</button></div><div class="result" id="pcres">Increase: 25%.</div></div>`;
if(id==='calc')return `<h1>Smart Calculator</h1><p class="sub">A proper four-operation calculator with addition, subtraction, multiplication, division, percentage, decimals and parentheses.</p><div class="calc-shell"><input class="calc-display" id="calcdisplay" value="0" inputmode="decimal" aria-label="Calculator display"><div class="calc-keys" id="calckeys"><button class="calc-key clear" data-k="C">C</button><button class="calc-key" data-k="⌫">⌫</button><button class="calc-key op" data-k="%">%</button><button class="calc-key op" data-k="÷">÷</button><button class="calc-key" data-k="7">7</button><button class="calc-key" data-k="8">8</button><button class="calc-key" data-k="9">9</button><button class="calc-key op" data-k="×">×</button><button class="calc-key" data-k="4">4</button><button class="calc-key" data-k="5">5</button><button class="calc-key" data-k="6">6</button><button class="calc-key op" data-k="−">−</button><button class="calc-key" data-k="1">1</button><button class="calc-key" data-k="2">2</button><button class="calc-key" data-k="3">3</button><button class="calc-key plus" data-k="+">+</button><button class="calc-key" data-k="0">0</button><button class="calc-key" data-k=".">.</button><button class="calc-key" data-k="(">(</button><button class="calc-key" data-k=")">)</button><button class="calc-key" data-k="00">00</button><button class="calc-key" data-k="+/-">+/-</button><button class="calc-key op" data-k="ANS">ANS</button><button class="calc-key eq" data-k="=">=</button></div><div class="result" id="calcresult">Ready.</div></div>`;
if(id==='units')return `<h1>Unit Converter</h1><p class="sub">Fast conversion for length, weight, temperature and area.</p><div class="box"><div class="row"><div class="field"><label>Category</label><select id="ucat"><option>Length</option><option>Weight</option><option>Temperature</option><option>Area</option></select></div><div class="field"><label>Value</label><input id="uval" type="number" step="any" value="1"></div></div><div class="row" style="margin-top:12px"><div class="field"><label>From</label><select id="ufrom"></select></div><div class="field"><label>To</label><select id="uto"></select></div></div><div class="result" id="ures">1 Meter = 1 Meter</div></div>`;
if(id==='discount')return `<h1>Discount Calculator</h1><p class="sub">Know exactly what you pay and what you save.</p><div class="box"><div class="row"><div class="field"><label>Original price</label><input id="dprice" type="number" min="0" step="any" value="1000"></div><div class="field"><label>Discount %</label><input id="dpercent" type="number" min="0" step="any" value="20"></div></div><div class="actions"><button class="primary" id="dgo">Calculate</button></div><div class="stats"><div class="stat"><span>FINAL PRICE</span><b id="dfinal">₹800.00</b></div><div class="stat"><span>YOU SAVE</span><b id="dsave">₹200.00</b></div><div class="stat"><span>DISCOUNT</span><b id="drate">20%</b></div></div></div>`;
if(id==='emi')return `<h1>EMI Calculator</h1><p class="sub">Estimate your monthly loan payment and total interest.</p><div class="box"><div class="row"><div class="field"><label>Loan amount (₹)</label><input id="eprincipal" type="number" value="500000"></div><div class="field"><label>Annual interest (%)</label><input id="erate" type="number" step="0.01" value="8.5"></div></div><div class="row" style="margin-top:12px"><div class="field"><label>Tenure (years)</label><input id="eyears" type="number" step="0.5" value="5"></div></div><div class="actions"><button class="primary" id="emigo">Calculate EMI</button></div><div class="stats"><div class="stat"><span>MONTHLY EMI</span><b id="emiout">₹10,258</b></div><div class="stat"><span>TOTAL INTEREST</span><b id="eiout">₹115,480</b></div><div class="stat"><span>TOTAL PAYMENT</span><b id="etout">₹615,480</b></div></div></div>`;
if(id==='bmi')return `<h1>BMI Calculator</h1><p class="sub">Enter your height and weight for a quick BMI result.</p><div class="box"><div class="row"><div class="field"><label>Height (cm)</label><input id="bh" type="number" value="170"></div><div class="field"><label>Weight (kg)</label><input id="bw" type="number" value="65"></div></div><div class="actions"><button class="primary" id="bmigo">Calculate BMI</button></div><div class="result" id="bmiout">BMI 22.49 — Normal range.</div></div>`;
if(id==='password')return `<h1>Password Generator</h1><p class="sub">Create strong random passwords locally. Nothing is uploaded.</p><div class="box"><div class="field"><label>Length: <span id="plenout">18</span></label><input class="range" id="plen" type="range" min="8" max="64" value="18"></div><div class="row" style="margin-top:15px"><label><input id="pupper" type="checkbox" checked> Uppercase</label><label><input id="plower" type="checkbox" checked> Lowercase</label><label><input id="pnums" type="checkbox" checked> Numbers</label><label><input id="psym" type="checkbox" checked> Symbols</label></div><div class="result" id="passout" style="word-break:break-all">Generating…</div><div class="actions"><button class="primary" id="newpass">Generate new</button><button class="secondary" id="copypass">Copy</button></div></div>`;
return `<h1>Text Counter</h1><p class="sub">Instant word, character, line and reading-time counts.</p><div class="box"><div class="field"><label>Your text</label><textarea id="wtext" placeholder="Start typing…"></textarea></div><div class="stats"><div class="stat"><span>WORDS</span><b id="wc">0</b></div><div class="stat"><span>CHARACTERS</span><b id="cc">0</b></div><div class="stat"><span>LINES</span><b id="lc">0</b></div></div><div class="result">Estimated reading time: <strong id="rt" style="display:inline;font-size:16px">0 min</strong></div></div>`;
}
const init={
pdf:()=>{const get=setupFiles('pdf');$('#pdfclear').onclick=()=>{get.clear();$('#pdfpreview').innerHTML='';$('#pdfres').textContent='Ready.';$('#pmeter').style.width='0'};$('#pdfgo').onclick=async()=>{const fs=get.files();const target=Math.max(20,+$('#ptarget').value||100)*1024;const res=$('#pdfres');const meter=$('#pmeter');if(!fs.length){res.textContent='Please choose at least one image.';return}res.textContent='Optimizing PDF…';let best=null;for(let pass=0;pass<18;pass++){const scale=Math.max(.12,Math.pow(.78,pass));const q=Math.max(.12,.9-pass*.045);const imgs=[];for(const f of fs){const bmp=await createImageBitmap(f);const maxW=1200*scale,maxH=1600*scale,s=Math.min(1,maxW/bmp.width,maxH/bmp.height);const c=document.createElement('canvas');c.width=Math.max(70,Math.round(bmp.width*s));c.height=Math.max(70,Math.round(bmp.height*s));const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(bmp,0,0,c.width,c.height);const blob=await canvasBlob(c,q);imgs.push({bytes:new Uint8Array(await blob.arrayBuffer()),w:c.width,h:c.height})}const pdf=makePDF(imgs,$('#pformat').value);best=pdf;meter.style.width=Math.min(100,pdf.length/target*100)+'%';res.textContent=`Pass ${pass+1} · ${(pdf.length/1024).toFixed(1)} KB`;if(pdf.length<=target)break}const blob=new Blob([best],{type:'application/pdf'});downloadBlob(blob,'harsh-tools-under-'+$('#ptarget').value+'kb.pdf');res.innerHTML=`<strong>${(best.length/1024).toFixed(1)} KB</strong>${best.length<=target?'✓ Target achieved.':'Best readable result reached — increase target or reduce images.'}`}},
age:()=>{const today=new Date();$('#agedate').valueAsDate=today;$('#agego').onclick=()=>{const d=new Date($('#dob').value+'T00:00:00');const end=new Date($('#agedate').value+'T00:00:00');if(isNaN(d)||isNaN(end)||d>end){$('#ageres').textContent='Please enter valid dates.';return}let y=end.getFullYear()-d.getFullYear(),m=end.getMonth()-d.getMonth(),day=end.getDate()-d.getDate();if(day<0){m--;day+=new Date(end.getFullYear(),end.getMonth(),0).getDate()}if(m<0){y--;m+=12}$('#ageres').innerHTML=`<strong>${y} years, ${m} months, ${day} days</strong>`+`Exact age as of ${end.toLocaleDateString()}.`}},
percent:()=>{$('#pgo').onclick=()=>{const x=+$('#px').value,y=+$('#py').value;$('#pres').innerHTML=`<strong>${fmt(x*y/100)}</strong>${x}% of ${fmt(y)} = ${fmt(x*y/100)}`};$('#pchange').onclick=()=>{const a=+$('#pold').value,b=+$('#pnew').value;if(a===0){$('#pcres').textContent='Original value cannot be zero.';return}const c=(b-a)/Math.abs(a)*100;$('#pcres').innerHTML=`<strong>${c>=0?'Increase':'Decrease'}: ${Math.abs(c).toFixed(2)}%</strong>${fmt(a)} → ${fmt(b)}`}},
calc:()=>{const e=$('#calcdisplay'),keys=$('#calckeys'),r=$('#calcresult');let ans=0,solved=false;function set(v){e.value=v||'0'}function press(k){let v=e.value;if(k==='C'){set('0');solved=false;return}if(k==='⌫'){set(v.length>1?v.slice(0,-1):'0');solved=false;return}if(k==='ANS'){v=solved?String(ans):v;set(v);return}if(k==='+/-'){if(v==='0')return;const m=v.match(/(?:^|[+\-×÷(])(-?\d*\.?\d+)$/);if(m){const old=m[1],rep=old.startsWith('-')?old.slice(1):'-'+old;set(v.slice(0,v.length-old.length)+rep)}return}if(k==='='){try{ans=evaluate(v);set(fmt(ans));r.innerHTML=`<strong>${fmt(ans)}</strong>${v} = ${fmt(ans)}`;solved=true}catch(err){r.textContent=err.message||'Invalid expression';solved=false}return}if(k==='%'){if(v==='0')return;const m=v.match(/(\d+(?:\.\d+)?)$/);if(m)set(v.slice(0,v.length-m[1].length)+String(+m[1]/100));solved=false;return}if(/[+\-×÷]/.test(k)&&/[+\-×÷]$/.test(v))v=v.slice(0,-1);if(solved&&/[0-9.]/.test(k)){v='';solved=false}if(k==='00'&&v==='0')return;if(k==='.'&&v.split(/[+\-×÷()]/).at(-1).includes('.'))return;set((v==='0'&&/[0-9]/.test(k))?k:v+k);solved=false}keys.addEventListener('click',e=>{const b=e.target.closest('[data-k]');if(b)press(b.dataset.k)});e.addEventListener('keydown',ev=>{const map={Enter:'=',Escape:'C',Backspace:'⌫','*':'×','/':'÷','-':'−'};if(map[ev.key]||/[0-9+%().]/.test(ev.key)){ev.preventDefault();press(map[ev.key]||ev.key)}});},
units:()=>{const data={Length:{Meter:1,Kilometer:1000,Centimeter:.01,Millimeter:.001,Foot:.3048,Inch:.0254,Mile:1609.344},Weight:{Kilogram:1,Gram:.001,Pound:.45359237,Ounce:.0283495231},Area:{SquareMeter:1,SquareKilometer:1e6,SquareFoot:.09290304,SquareYard:.83612736,Acre:4046.8564224,Hectare:10000},Temperature:{Celsius:'C',Fahrenheit:'F',Kelvin:'K'}};function fill(){const cat=$('#ucat').value,o=Object.keys(data[cat]);$('#ufrom').innerHTML=o.map(x=>`<option>${x}</option>`).join('');$('#uto').innerHTML=o.map(x=>`<option>${x}</option>`).join('');convert()}function convert(){const cat=$('#ucat').value,v=+$('#uval').value||0,a=$('#ufrom').value,b=$('#uto').value;if(cat==='Temperature'){let c=a==='Celsius'?v:a==='Fahrenheit'?(v-32)*5/9:v-273.15;let out=b==='Celsius'?c:b==='Fahrenheit'?c*9/5+32:c+273.15;$('#ures').innerHTML=`<strong>${fmt(out,6)} ${b}</strong>`}else $('#ures').innerHTML=`<strong>${fmt(v*data[cat][a]/data[cat][b],8)} ${b}</strong>`}$('#ucat').onchange=fill;$('#uval').oninput=convert;$('#ufrom').onchange=convert;$('#uto').onchange=convert;fill()},
discount:()=>{$('#dgo').onclick=()=>{const p=Math.max(0,+$('#dprice').value||0),d=Math.max(0,+$('#dpercent').value||0),save=p*d/100;$('#dfinal').textContent='₹'+money(p-save);$('#dsave').textContent='₹'+money(save);$('#drate').textContent=Math.min(100,d).toFixed(2).replace(/\.00$/,'')+'%'}},
emi:()=>{$('#emigo').onclick=()=>{const P=Math.max(0,+$('#eprincipal').value||0),annual=Math.max(0,+$('#erate').value||0),years=Math.max(0,+$('#eyears').value||0),n=Math.round(years*12),r=annual/1200;let emi;if(!n){emi=0}else if(!r)emi=P/n;else emi=P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1);const total=emi*n;$('#emiout').textContent='₹'+money(emi);$('#eiout').textContent='₹'+money(total-P);$('#etout').textContent='₹'+money(total)}},
bmi:()=>{$('#bmigo').onclick=()=>{const h=+$('#bh').value/100,w=+$('#bw').value;if(h<=0||w<=0){$('#bmiout').textContent='Enter valid height and weight.';return}const bmi=w/(h*h);let label=bmi<18.5?'Underweight':bmi<25?'Normal range':bmi<30?'Overweight':'Obesity';$('#bmiout').innerHTML=`<strong>BMI ${bmi.toFixed(2)}</strong>${label}`}},
password:()=>{const out=$('#passout'),gen=()=>{let chars='';if($('#pupper').checked)chars+='ABCDEFGHIJKLMNOPQRSTUVWXYZ';if($('#plower').checked)chars+='abcdefghijklmnopqrstuvwxyz';if($('#pnums').checked)chars+='0123456789';if($('#psym').checked)chars+='!@#$%^&*()_+-=[]{}';if(!chars){out.textContent='Select at least one character set.';return}const a=new Uint32Array(+$('#plen').value);crypto.getRandomValues(a);let s='';for(const n of a)s+=chars[n%chars.length];out.textContent=s};$('#plen').oninput=e=>$('#plenout').textContent=e.target.value;$('#newpass').onclick=gen;$('#copypass').onclick=async()=>{try{await navigator.clipboard.writeText(out.textContent);$('#copypass').textContent='Copied ✓';setTimeout(()=>$('#copypass').textContent='Copy',1000)}catch{}};gen()},
words:()=>{$('#wtext').oninput=()=>{const s=$('#wtext').value,words=s.trim()?s.trim().split(/\s+/).length:0;$('#wc').textContent=words;$('#cc').textContent=s.length;$('#lc').textContent=s?s.split(/\r\n|\r|\n/).length:0;$('#rt').textContent=(words/200).toFixed(1)+' min'}}
};
function setupFiles(kind){let arr=[];const input=$('#'+kind+'files'),drop=$('#'+kind+'drop'),prev=$('#'+kind+'preview');function render(fs){arr=[...fs].filter(f=>f.type.startsWith('image/'));prev.innerHTML='';arr.forEach(f=>{const u=URL.createObjectURL(f),d=document.createElement('div');d.className='thumb';d.innerHTML=`<img src="${u}"><span>${(f.size/1024).toFixed(0)} KB</span>`;prev.appendChild(d)})}input.onchange=e=>render(e.target.files);['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>render(e.dataTransfer.files));return{files:()=>arr,clear:()=>{arr=[];input.value=''}}}
function canvasBlob(c,q){return new Promise(r=>c.toBlob(r,'image/jpeg',q))}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function fmt(n,max=2){if(!Number.isFinite(n))return 'Error';return Number(n.toFixed(max)).toLocaleString('en-IN',{maximumFractionDigits:max})}
function money(n){return Number(n).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function tokenize(s){const out=[];let i=0;while(i<s.length){if(/\s/.test(s[i])){i++;continue}if(/[0-9.]/.test(s[i])){let j=i;while(j<s.length&&/[0-9.]/.test(s[j]))j++;const v=s.slice(i,j);if((v.match(/\./g)||[]).length>1)throw Error('Invalid number');out.push({t:'n',v:+v});i=j;continue}if('+-×÷()'.includes(s[i])){out.push({t:s[i],v:s[i]});i++;continue}throw Error('Invalid character')}return out}
function evaluate(s){let tok=tokenize(s),arr=[];for(let i=0;i<tok.length;i++){const t=tok[i];if(t.t==='-'&&(i===0||['+','-','×','÷','('].includes(tok[i-1]?.t)))arr.push({t:'n',v:0}),arr.push({t:'-',v:'-'});else arr.push(t)}const prec={'+':1,'-':1,'×':2,'÷':2};const vals=[],ops=[];const apply=()=>{const op=ops.pop();const b=vals.pop(),a=vals.pop();if(op==='+')vals.push(a+b);else if(op==='-')vals.push(a-b);else if(op==='×')vals.push(a*b);else if(op==='÷'){if(b===0)throw Error('Cannot divide by zero');vals.push(a/b)}};for(const t of arr){if(t.t==='n')vals.push(t.v);else if(t.t==='(')ops.push(t.t);else if(t.t===')'){while(ops.length&&ops.at(-1)!=='(')apply();if(ops.pop()!=='(')throw Error('Mismatched parentheses')}else{while(ops.length&&ops.at(-1)!=='('&&prec[ops.at(-1)]>=prec[t.t])apply();ops.push(t.t)}}while(ops.length){if(ops.at(-1)==='(')throw Error('Mismatched parentheses');apply()}if(vals.length!==1||!Number.isFinite(vals[0]))throw Error('Invalid expression');return vals[0]}
function makePDF(imgs,format){const enc=new TextEncoder(),chunks=[];let total=0;const add=b=>{chunks.push(b);total+=b.length};add(enc.encode('%PDF-1.4\n%\xFF\xFF\xFF\xFF\n'));const pageIds=[],imgIds=[],contentIds=[];let id=3;imgs.forEach(()=>{pageIds.push(id++);imgIds.push(id++);contentIds.push(id++)});const obj=[];obj[1]='<< /Type /Catalog /Pages 2 0 R >>';obj[2]=`<< /Type /Pages /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] /Count ${pageIds.length} >>`;const PW=format==='letter'?612:595,PH=format==='letter'?792:842;imgs.forEach((im,i)=>{const scale=Math.min(PW/im.w,PH/im.h),w=im.w*scale,h=im.h*scale,x=(PW-w)/2,y=(PH-h)/2;obj[pageIds[i]]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PW} ${PH}] /Resources << /XObject << /Im${i} ${imgIds[i]} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`;obj[contentIds[i]]={stream:`q ${w.toFixed(2)} 0 0 ${h.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm /Im${i} Do Q`};obj[imgIds[i]]={image:im}});const offsets=[0];for(let i=1;i<obj.length;i++){offsets[i]=total;add(enc.encode(`${i} 0 obj\n`));const o=obj[i];if(typeof o==='string')add(enc.encode(o+'\nendobj\n'));else if(o.stream){const b=enc.encode(o.stream);add(enc.encode(`<< /Length ${b.length} >>\nstream\n`));add(b);add(enc.encode('\nendstream\nendobj\n'))}else{const b=o.image.bytes;add(enc.encode(`<< /Type /XObject /Subtype /Image /Width ${o.image.w} /Height ${o.image.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${b.length} >>\nstream\n`));add(b);add(enc.encode('\nendstream\nendobj\n'))}}const start=total;let xref=`xref\n0 ${obj.length}\n0000000000 65535 f \n`;for(let i=1;i<obj.length;i++)xref+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';xref+=`trailer\n<< /Size ${obj.length} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;add(enc.encode(xref));const out=new Uint8Array(total);let p=0;for(const b of chunks){out.set(b,p);p+=b.length}return out}
})();
